using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using EFT;
using SPT.Reflection.Patching;
using SPTQuestingBots.Components.Spawning;

namespace SPTQuestingBots.Patches.Spawning
{
    public class GetAllBossPlayersPatch : ModulePatch
    {
        protected override MethodBase GetTargetMethod()
        {
            return typeof(BotSpawner).GetMethod(nameof(BotSpawner.GetAllBossPLayers), BindingFlags.Public | BindingFlags.Instance);
        }

        [PatchPrefix]
        protected static bool PatchPrefix(ref List<Player> __result, List<Player> ___AllPlayers)
        {
            // Return all boss players except those generated by our mod.
            // The old filter (!p.IsAI) removed ALL AI bosses including real
            // game bosses like Killa and Reshala.
            IEnumerable<string> modBotIds = BotGenerator.GetAllGeneratedBotProfileIDs();
            __result = ___AllPlayers.Where(p => (p.AIData?.IAmBoss == true) && !(p.IsAI && modBotIds.Contains(p.Profile.Id))).ToList();

            return false;
        }
    }
}
